# 블로그 기본 설정
title: Groovejm 블로그
description: 개인 공부를 위한 블로그 
author: JM

# 테마 설정
theme: jekyll-theme-minimal

# 한국어 설정
lang: ko-KR
timezone: Asia/Seoul

# 기본 URL 설정
baseurl: ""
url: "https://groovejm.github.io"
  
